apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wallet-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wallet-service
  minReplicas: 1
  maxReplicas: 1
