apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: h2db-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: h2db-service
  minReplicas: 1
  maxReplicas: 1
